# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        
      - name: Create config json file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ".contentful.json"
          json: ${{ secrets.CTF_JSON }}
          
      - name: Build
        run: npm run generate

      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist
          key: build-result-${{ hashFiles('package-lock.json') }}

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist
          key: build-result-${{ hashFiles('package-lock.json') }}
          restore-keys: build-result-

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
